### ISSUE TITLE
why calibration data needed?

### ISSUE THREAD

**Issue by dongje** [vllm-project/llm-compressor#741]
sorry for my basic question

awq dosen't work for my gpu so i'd like to use it

but unlike llm.generate , it seems to need calibration data for oneshot
but i don't know why this data and process is needed. can you explain for me? thank you

**Comment by kylesayrs** [comment]
Hi Dongje!

A calibration set is required to use the AWQ modifier because the [Activation-aware Weight Quantization (AWQ)](https://arxiv.org/pdf/2306.00978) algorithm requires information about the typical activations of neurons within the model in order to perform its optimal weight quantization.

Feel free to reopen this issue if you have any further questions!
